[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"

[project]
name = "biocol"
version = "0.1.0"
description = "Backend para análisis y procesamiento de BLAST"
requires-python = ">=3.10"
dependencies = [
    "biopython>=1.83",
    "pandas>=2.0",
]

[project.scripts]
biocol = "biocol.cli.main:console"

[project.optional-dependencies]
dev = [
    "pytest>=8.0",
]

[tool.setuptools.packages.find]
where = ["src"]

[tool.pytest.ini_options]
testpaths = ["tests"]
pythonpath = ["src"]
log_cli = true
log_cli_level = "INFO"
